const CONSTANTS = {
  PLACE_TYPE_RESTAURANT: "restaurant",
  PLACE_TYPE_CAFE: "cafe",
  PLACE_TYPE_ATM: "atm",

  PLACE_TYPE_AIRPORT: "airport",
  PLACE_TYPE_BUS_STATION: "bus_station",
  PLACE_TYPE_CAR_RENTAL: "car_rental",
  PLACE_TYPE_LIGHT_RAIL_STATION: "light_rail_station",
  PLACE_TYPE_PARKING: "parking",
  PLACE_TYPE_RV_PARK: "rv_park",
  PLACE_TYPE_SUBWAY_STATION: "subway_station",
  PLACE_TYPE_TAXI_STAND: "taxi_stand",
  PLACE_TYPE_TRAIN_STATION: "train_station",
  PLACE_TYPE_TRANSIT_STATION: "transit_station",
  PLACE_TYPE_TRAVEL_AGENCY: "travel_agency",
  PLACE_TYPE_GAS_STATION: "gas_station",

  GALLE_ATTRACTION_1: "6.030296341501824,80.21600656443266",
  GALLE_ATTRACTION_2: "6.025180791448571,80.218041686873",
  HIKKADUWA_ATTRACTION_1: "6.13804757204398,80.09905628813596",
  HIKKADUWA_ATTRACTION_2: "6.1333045364175165,80.09981753936195",
  COASTAL_CITIES: ["galle", "hikkaduwa", "unawatuna"],
  COASTAL_PROVINCE: ["southern province", "western province"],
  MODELS: ["COASTAL", "URBAN", "CENTRAL", "HISTORIC"],
  PLACES_URL: "https://maps.googleapis.com/maps/api/place/nearbysearch/json?",
  DISTANCE_URL: "https://maps.googleapis.com/maps/api/directions/json?",
  GEOCODE_URL: "https://maps.googleapis.com/maps/api/geocode/json?",
  LANGUAGE: "en",
  FLASK_API_URL: "http://localhost:5000",
  LOCATION_POPULARITY_MODEL: "popularity",
  DEMAND_MODEL: "demand",
};

module.exports = CONSTANTS;
